### PR TITLE
Corrected a few small details

### PR DESCRIPTION
**Pull request by Ratstail91**
Hey!

I was poking through this, and I'm quite impressed with what you've done! I did, however notice a few small problems here and there, so I figured I'd fix them up for you.

I've also added a big file from Airport for testing (this thing generates the game map), there weren't many issues that needed fixing, though.

When you think this is ready, clean it up, and I'd be happy to include this in Toy's `tools/` directory - just open a pull request on the main repo, so your contributions are tracked.

A few small requests:

* I prefer tabs over spaces
* There should be three sections highlighted (literals, functions, code), not just two (you include the function definitions as part of the literals section).

### CODE REVIEW

**Comment by hiperiondev** [comment]
in line 352:
   printf("%d\t", i);

breaks the format.
what's its purpose?

**Comment by hiperiondev** [comment]
- There should be three sections highlighted (literals, functions, code), not just two (you include the function definitions as part of the literals section).

It is that way because, in fact, the functions are in the definition header of the literals.
But I agree that it should be shown as a separate section.
Also change the format to be able to make an assembler that can reverse the process.

**Comment by Ratstail91** [comment]
> in line 352: printf("%d\t", i);
> 
> breaks the format. what's its purpose?

This is so you can identify the literals by index, since they're only referenced below by index.

**Comment by hiperiondev** [comment]
I have corrected it so that it looks more consistent with the format

**Pull request merged**
